run:
  timeout: 3m
linters-settings:
  depguard:
    rules:
      allow_repos:
        allow:
          - github.com/packruler/rewrite-body/handler
          - github.com/packruler/rewrite-body/compressutil
          - bytes
          - context
          - fmt
          - net/http
          - net/http/httptest
          - regexp
          - strconv
          - strings
          - testing
  gocyclo:
    min-complexity: 12
  goconst:
    min-len: 3
    min-occurrences: 4
  misspell:
    locale: US
  funlen:
    lines: 60
    statements: 40
linters:
  enable-all: true
  disable:
    - bodyclose
    - wrapcheck
    - testpackage
    - paralleltest
    - tparallel
issues:
  exclude-use-default: false
  max-same-issues: 0
  exclude:
    - don't use an underscore in package name
    - "ST1003: should not use underscores in package names"
    - "SA1019: http.CloseNotifier has been deprecated since Go 1.11 and an alternative has been available since Go 1.7: the CloseNotifier interface predates Go's context package. New code should use Request.Context instead."
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst
        - funlen
        - godot
        - lll
        - exhaustruct
    - path: themepark.go
      linters:
        - exhaustruct
  exclude-files:
    - httputil/header/header.go
    - apps/app_name.go
    - themes/theme_name.go
